# Generated by Django 4.0 on 2021-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_availabletiming_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletiming',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
