# Generated by Django 4.0 on 2021-12-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_availabletiming_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletiming',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
