# Generated by Django 4.0 on 2021-12-19 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_n', models.BooleanField(default=False)),
                ('n_t', models.BooleanField(default=False)),
                ('t_e', models.BooleanField(default=False)),
                ('e_t', models.BooleanField(default=False)),
                ('t_o', models.BooleanField(default=False)),
                ('o_t', models.BooleanField(default=False)),
                ('t_th', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customuser')),
            ],
        ),
    ]
